/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DreRouteImport } from './routes/dre'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DreRoute = DreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/automacoes': typeof AutomacoesRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dre': typeof DreRoute
  '/financeiro': typeof FinanceiroRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/automacoes': typeof AutomacoesRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dre': typeof DreRoute
  '/financeiro': typeof FinanceiroRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/automacoes': typeof AutomacoesRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dre': typeof DreRoute
  '/financeiro': typeof FinanceiroRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/automacoes'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/dre'
    | '/financeiro'
    | '/projetos'
    | '/relatorios'
    | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/automacoes'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/dre'
    | '/financeiro'
    | '/projetos'
    | '/relatorios'
    | '/tarefas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/automacoes'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/dre'
    | '/financeiro'
    | '/projetos'
    | '/relatorios'
    | '/tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AutomacoesRoute: typeof AutomacoesRoute
  ClientesRoute: typeof ClientesRoute
  ComercialRoute: typeof ComercialRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DreRoute: typeof DreRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ProjetosRoute: typeof ProjetosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TarefasRoute: typeof TarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dre': {
      id: '/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof DreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AutomacoesRoute: AutomacoesRoute,
  ClientesRoute: ClientesRoute,
  ComercialRoute: ComercialRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DreRoute: DreRoute,
  FinanceiroRoute: FinanceiroRoute,
  ProjetosRoute: ProjetosRoute,
  RelatoriosRoute: RelatoriosRoute,
  TarefasRoute: TarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
